baseurl = "https://byronz.github.io"
languageCode = "en-us"
title = "雜"
theme = "hucore"
copyright = "&copy; 2017 | 朱曉清 | <small>powered by</small> <a href=\"gohugo.io\" target=\"_blank\">Hugo</a>"
# googleAnalytics = "trackingcode"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "tech blog"
keywords = ["language", "programming", "automation"]
author = "Byron ZHU"
sharingicons = true
displayauthor = true
fontbody = "Hiragino Sans GB"

[params.highlight]
style = "solarized-dark"
languages = ["python", "bash", "json", "java", "yaml", "elixir", "scala"]

[[params.social]]
url = "https://github.com/byronz"
fa_icon = "fa-github"

[[params.social]]
url = "https://linkedin.com/in/byronzhu"
fa_icon = "fa-linkedin-square"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

[[params.socialshare]]
url = "https://linkedin.com/in/byronzhu"
fa_icon = "fa-linkedin-square"